# Generated by Django 5.2.4 on 2025-07-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='languages',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
    ]
