# Generated by Django 5.2.4 on 2025-07-20 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_description_problem_languages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='problem',
            name='acceptance_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='submissions',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
