# Generated by Django 5.2.4 on 2025-07-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_options_problem_acceptance_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='c_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='cpp_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='follow_up',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='java_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='javascript_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='python_template',
            field=models.TextField(blank=True),
        ),
    ]
