# Generated by Django 5.2.4 on 2025-07-27 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_c_template_problem_constraints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='runtime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_cases_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_test_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem')),
            ],
        ),
    ]
