# Generated by Django 5.2.4 on 2025-07-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_community_user',
            field=models.BooleanField(default=False),
        ),
    ]
